defaults:
  - template_libero_motion
  - _self_

name: libero_90_test_framestride_3

hdf5_path_globs: ${oc.env:LIBERO_ROOT}/${.name}/*.hdf5
buffer_path: ${oc.env:LIBERO_BUFFER_ROOT}/${.name}/buffer.zarr