defaults:
  - template_libero
  - _self_

name: libero_90_test_framestride_3
# hdf5_path_globs: /home/ubuntu/LIBERO/libero/datasets/libero_90/*.hdf5
# buffer_path: /home/ubuntu/LIBERO/libero/datasets/libero_90/buffer.zarr

hdf5_path_globs: ${oc.env:LIBERO_ROOT}/${name}/*.hdf5
buffer_path: ${oc.env:LIBERO_BUFFER_ROOT}/${name}/buffer.zarr